<a href="https://colab.research.google.com/github/Ram-Vidhu/Job_searcher_and_Resume_Enhancer/blob/Dev/Notebooks/GenAI_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

# Example: Reading a CSV stored inside "My Drive"
job_skills = pd.read_csv('/content/drive/MyDrive/1.3M_Linkedin/job_skills.csv')
job_skills.head()

,job_link,job_skills
0,https://www.linkedin.com/jobs/view/housekeeper...,"Building Custodial Services, Cleaning, Janitor..."
1,https://www.linkedin.com/jobs/view/assistant-g...,"Customer service, Restaurant management, Food ..."
2,https://www.linkedin.com/jobs/view/school-base...,"Applied Behavior Analysis (ABA), Data analysis..."
3,https://www.linkedin.com/jobs/view/electrical-...,"Electrical Engineering, Project Controls, Sche..."
4,https://www.linkedin.com/jobs/view/electrical-...,"Electrical Assembly, Point to point wiring, St..."

In [ ]:
job_summary = pd.read_csv('/content/drive/MyDrive/1.3M_Linkedin/job_summary.csv')
job_summary.head()

,job_link,job_summary
0,https://www.linkedin.com/jobs/view/restaurant-...,Rock N Roll Sushi is hiring a Restaurant Manag...
1,https://www.linkedin.com/jobs/view/med-surg-re...,Schedule\n: PRN is required minimum 12 hours p...
2,https://www.linkedin.com/jobs/view/registered-...,Description\nIntroduction\nAre you looking for...
3,https://uk.linkedin.com/jobs/view/commercial-a...,Commercial account executive\nSheffield\nFull ...
4,https://www.linkedin.com/jobs/view/store-manag...,Address:\nUSA-CT-Newington-44 Fenn Road\nStore...

In [ ]:
linkedin_job_postings = pd.read_csv('/content/drive/MyDrive/1.3M_Linkedin/linkedin_job_postings.csv')
linkedin_job_postings.head()

,job_link,last_processed_time,got_summary,got_ner,is_being_worked,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/account-exe...,2024-01-21 07:12:29.00256+00,t,t,f,Account Executive - Dispensing (NorCal/Norther...,BD,"San Diego, CA",2024-01-15,Coronado,United States,Color Maker,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/registered-...,2024-01-21 07:39:58.88137+00,t,t,f,Registered Nurse - RN Care Manager,Trinity Health MI,"Norton Shores, MI",2024-01-14,Grand Haven,United States,Director Nursing Service,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/restaurant-...,2024-01-21 07:40:00.251126+00,t,t,f,RESTAURANT SUPERVISOR - THE FORKLIFT,Wasatch Adaptive Sports,"Sandy, UT",2024-01-14,Tooele,United States,Stand-In,Mid senior,Onsite
3,https://www.linkedin.com/jobs/view/independent...,2024-01-21 07:40:00.308133+00,t,t,f,Independent Real Estate Agent,Howard Hanna | Rand Realty,"Englewood Cliffs, NJ",2024-01-16,Pinehurst,United States,Real-Estate Clerk,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/group-unit-...,2024-01-19 09:45:09.215838+00,f,f,f,Group/Unit Supervisor (Systems Support Manager...,"IRS, Office of Chief Counsel","Chamblee, GA",2024-01-17,Gadsden,United States,Supervisor Travel-Information Center,Mid senior,Onsite

In [ ]:
merge1 = pd.merge(job_skills,job_summary,on='job_link',how='inner')
merge2 = pd.merge(merge1,linkedin_job_postings,on='job_link',how='inner')
merge2.drop(['last_processed_time','got_summary','got_ner','is_being_worked'],axis=1,inplace=True)
merge2.head()

,job_link,job_skills,job_summary,job_title,company,job_location,first_seen,search_city,search_country,search_position,job_level,job_type
0,https://www.linkedin.com/jobs/view/housekeeper...,"Building Custodial Services, Cleaning, Janitor...",Department:\nBuilding Custodial Services\nSala...,Housekeeper I - PT,Jacksonville State University,Metro Jacksonville,2024-01-12,Jacksonville,United States,Cleaner,Mid senior,Onsite
1,https://www.linkedin.com/jobs/view/assistant-g...,"Customer service, Restaurant management, Food ...",Summary Of Key Responsibilities\nThis position...,Assistant General Manager - Huntington 4131,Ruby Tuesday,"Barboursville, WV",2024-01-13,West Virginia,United States,Clerk General,Mid senior,Onsite
2,https://www.linkedin.com/jobs/view/school-base...,"Applied Behavior Analysis (ABA), Data analysis...",Make a difference every day by joining CCRES a...,School-based Behavior Analyst,CCRES Educational and Behavioral Health Services,"Boyertown, PA",2024-01-13,Exeter,United States,Consultant Education,Mid senior,Onsite
3,https://www.linkedin.com/jobs/view/electrical-...,"Electrical Engineering, Project Controls, Sche...",Requisition ID: 271524\nRelocation Authorized:...,Electrical Deputy Engineering Group Supervisor,Energy Jobline,"Ogden, UT",2024-01-12,Layton,United States,Cleaner,Mid senior,Onsite
4,https://www.linkedin.com/jobs/view/electrical-...,"Electrical Assembly, Point to point wiring, St...",Job Description\nProduction Specialist\nElectr...,Electrical Assembly Lead,Sanmina,"Pleasant Prairie, WI",2024-01-12,North Chicago,United States,Assembly Technician,Mid senior,Onsite